New version of mkcert

diff --git a/distros/debian/mkcert/mkcert b/distros/debian/mkcert/mkcert
--- a/distros/debian/mkcert/mkcert
+++ b/distros/debian/mkcert/mkcert
@@ -1,111 +1,194 @@
 #!/usr/bin/env bash
-
 #
 # Script for mkcert to help its use.
-#
-if [[ -z "$1" ]]; then
-  CURRENT_OPTION="help"
-elif [[ "$1" =~ ^(create|delete|list|upgrade|version)$ ]]; then
-  CURRENT_OPTION="$1"
-  shift
-  if [[ "$CURRENT_OPTION" =~ ^(create|delete|upgrade)$ ]]; then
-    if [[ "$(id -u)" -ne "0" ]]; then
-      echo "Please, run this with the root user or sudo."
-      exit 1
-    elif [[ "$CURRENT_OPTION" != "upgrade" && $# -eq 0 ]]; then
-      echo "Missing domains for \"$CURRENT_OPTION\" option"
-      exit 1
-    fi
-  fi
+
+if [[ "$(id -u)" -ne "0" ]]; then
+  echo "Please, run this with the root user or sudo."
+  exit 1
 fi
 
 # A custom location is permitted.
 export CAROOT="${CAROOT:-/opt/mkcert/share}"
 
-mkdir -p /opt/mkcert/certificates
-
-case "${CURRENT_OPTION:-help}" in
-create | delete)
-  while [[ "$#" -gt "0" ]]; do
-    CURRENT_DOMAIN="$1"
-    CURRENT_MESSAGE="Invalid format for \"$CURRENT_DOMAIN\" domain"
-    shift
-    if echo "$CURRENT_DOMAIN" | grep -qP "^[\w\-]+\.[\w]+$"; then
-      PEM_FILE="/opt/mkcert/certificates/$CURRENT_DOMAIN.pem"
-      KEY_FILE="/opt/mkcert/certificates/$CURRENT_DOMAIN.key"
-      case "$CURRENT_OPTION" in
-      create)
-        if [[ -f "${PEM_FILE}" ]]; then
-          CURRENT_ACTION="Upgrading"
-        fi
-        CURRENT_MESSAGE="${CURRENT_ACTION:-Creating} \"$CURRENT_DOMAIN\" domain certificate"
-        /opt/mkcert/bin/current \
-          -ecdsa \
-          -cert-file "$PEM_FILE" \
-          -key-file "$KEY_FILE" \
-          "$CURRENT_DOMAIN" "*.$CURRENT_DOMAIN" >/dev/null 2>&1 &&
-          cat "$KEY_FILE" "$PEM_FILE" | tee "$PEM_FILE" >/dev/null 2>&1 && {
-          CURRENT_ACTION_STATUS="DONE"
-          rm -f "$KEY_FILE"
-        }
-        CURRENT_MESSAGE+=" [${CURRENT_ACTION_STATUS:-ERROR}]"
-        ;;
-      delete)
-        if [[ -f "$PEM_FILE" || -f "$KEY_FILE" ]]; then
-          CURRENT_ACTION="Deleting"
-          find /opt/mkcert/certificates -name "*$CURRENT_DOMAIN*" -delete
-        fi
-        CURRENT_MESSAGE="${CURRENT_ACTION:-Missing} \"$CURRENT_DOMAIN\" domain certificate"
-        ;;
-      esac
-    fi
-    echo "$CURRENT_MESSAGE"
-  done
-  ;;
-upgrade)
-  CURRENT_ACTION="Upgrading"
-  if [[ ! -f /opt/mkcert/bin/current ]]; then
-    CURRENT_ACTION="Installing"
-    mkdir -p /opt/mkcert/bin
-  fi
-  echo "$CURRENT_ACTION the mkcert binary"
-  if wget -q "https://dl.filippo.io/mkcert/latest?for=linux/$(uname -r | awk -F'-' '{print $(NF)}')" -O /opt/mkcert/bin/latest; then
-    chmod +x /opt/mkcert/bin/latest
-    # Recheck for security
-    if /opt/mkcert/bin/latest --help 2>&1 | grep -q 'CAROOT'; then
-      mv /opt/mkcert/bin/latest /opt/mkcert/bin/current
-      if ! [[ -f "$CAROOT/rootCA-key.pem" || -f "$CAROOT/rootCA.pem" ]]; then
-        rm -rf "$CAROOT"
-        find /etc/ssl/certs/ -name "*mkcert*" -delete
-        /opt/mkcert/bin/current -install >/dev/null 2>&1
-        wget -q https://curl.se/ca/cacert.pem -O /etc/ssl/cacert.pem
-        find /etc/ssl/certs/ -name "*mkcert*" -exec cat {} \; >>/etc/ssl/cacert.pem
-      fi
-      exit
-    fi
-  fi
-  echo "Some problem occurred while $CURRENT_ACTION the mkcert binary."
-  ;;
-list)
-  find /opt/mkcert/certificates -type f | awk -F"/" '{print "- "$NF}'
-  ;;
-version)
-  /opt/mkcert/bin/current --version
-  ;;
-*)
-  echo "Usage: sudo mkcert [option] domain.tld..."
+__mkcert__usage() {
+  echo "Usage: sudo mkcert [create|delete] domain.tld ..."
   echo
-  echo "* This command join key and pem files generated by mkcert on single file"
-  echo "  to use in SSLCertificateFile ( Apache Directive )"
-  echo "* The certificates are always willcards and"
-  echo "  saved to \"/opt/mkcert/certificates\""
+  echo "* This command join key and pem files generated by mkcert (filipoo)"
+  echo "  to use in SSLCertificateFile ( Apache Directive )."
+  echo "* The certificates are always willcards and saved to"
+  echo "  \"/opt/mkcert/certificates\""
   echo
-  echo "OPTIONS:"
-  echo " create  - Create or update if exists the certificates for domain.tld"
-  echo " delete  - Delete the certificates for domain.tld"
-  echo " help    - Print this text and exit"
-  echo " list    - List all created certificates"
-  echo " upgrade - Upgrade the mkcert binary to latest version"
+  echo "COMMANDS:"
+  echo " create  - Create or update if exists the certificates for domains."
+  echo " delete  - Delete the certificates for domains."
+  echo " list    - List all created certificates."
+  echo " install - Download and install the latest mkcert binary."
+  echo " upgrade - Upgrade the mkcert binary to latest version."
+  echo " cli     - The mkcert binary is called, use with caution."
   echo " version - Print the mkcert binary version"
-  ;;
-esac
+  echo " help    - Print this text and exit"
+  exit 1
+}
+
+__mkcert__install() {
+  local arch
+  local action="$1"
+  local found=false
+  case "$(uname -m)" in
+  aarch64 | arm64) arch="arm64" ;;
+  x86_64 | amd64) arch="amd64" ;;
+  *)
+    echo "Not implemented."
+    exit 1
+    ;;
+  esac
+  if [[ -f /opt/mkcert/bin/current ]]; then
+    found=true
+  elif [[ "$action" == "upgrade" ]]; then
+    action="install"
+  fi
+
+  case "$action" in
+  install) echo "Installing the binary." ;;
+  update) echo "Updating the binary." ;;
+  esac
+
+  if ! wget -q "https://dl.filippo.io/mkcert/latest?for=linux/$arch" -O /opt/mkcert/bin/latest; then
+    echo "ERROR: Downloading the latest binary."
+    exit 1
+  fi
+  chmod +x /opt/mkcert/bin/latest
+  if ! /opt/mkcert/bin/latest --help 2>&1 | grep -q "CAROOT"; then
+    echo "ERROR: The latest downloaded binary not is valid."
+    exit 1
+  fi
+
+  mv /opt/mkcert/bin/{latest,current}
+  if [[ "$found" == true ]] && ! [[ -f "$CAROOT/rootCA-key.pem" || -f "$CAROOT/rootCA.pem" ]]; then
+    echo "The rootCA files are missing, reinstalled. The certificates need to be recreated."
+    rm -f "$CAROOT/rootCA-key.pem" "$CAROOT/rootCA.pem"
+    /opt/mkcert/bin/current -uninstall >/dev/null 2>&1
+    update-ca-certificates --fresh >/dev/null 2>&1
+    found=false
+  fi
+
+  if [[ "$found" == false ]]; then
+    /opt/mkcert/bin/current -install >/dev/null 2>&1
+    local domain
+    while read -r domain; do
+      if [[ "$found" == false ]]; then
+        echo "Auto recreating all certificates."
+        found=true
+      fi
+      __mkcert create "$domain"
+    done < <(find /opt/mkcert/certificates -name "*.pem" -exec basename -as '.pem' {} \;)
+  fi
+}
+
+__mkcert() {
+  local command domains=()
+  local domain pem key certs_path="/opt/mkcert/certificates"
+
+  # We make sure that they exist.
+  mkdir -p /opt/mkcert/{bin,certificates,share}
+
+  while [[ $# -gt 0 ]]; do
+    case "$1" in
+    help) __mkcert__usage ;;
+    version | cli)
+      if [[ ! -f /opt/mkcert/bin/current ]]; then
+        echo "Missing mkcert binary, run sudo mkcert install"
+        exit 1
+      elif [[ "$1" == "version" ]]; then
+        /opt/mkcert/bin/current --version
+      else
+        shift
+        /opt/mkcert/bin/current "$@"
+      fi
+      exit 0
+      ;;
+    list)
+      find "$certs_path" -name "*.pem" | awk -F"/" '
+BEGIN { nlen = 30 }
+{
+  name = $NF
+  gsub(/\.pem/, "", name)
+  names[NR] = name
+  if (length(name) > nlen) {
+    nlen = length(name)
+  }
+  certs[NR] = $0
+}
+END {
+  if (NR == 0) {
+    print "No certificates found."
+    exit 1
+  }
+  if (nlen > 30) {
+    nlen += 2
+  }
+  printf "%-*s %s\n", nlen, "DOMAIN", "CERTIFICATE"
+  for (i=1; i<=NR; i++) {
+    printf "%-*s %s\n", nlen,  names[i], certs[i]
+  }
+}'
+      exit $?
+      ;;
+    create | delete) command="$1" ;;
+    install | upgrade) __mkcert__install "$1" ;;
+    *)
+      if [[ -z "$command" ]]; then
+        __mkcert__usage
+      elif ! echo "$1" | grep -qP "^[\w\-]+\.[\w]+$"; then
+        echo "Invalid format for \"$1\" domain, skipping"
+      else
+        domains+=("$1")
+      fi
+      ;;
+    esac
+    shift
+  done
+
+  if [[ ${#domains[@]} -eq 0 ]]; then
+    echo "One or more domains must be specified."
+    exit 1
+  fi
+
+  case "$command" in
+  delete)
+    for domain in "${domains[@]}"; do
+      find "$certs_path" -name "*$domain*" | awk -v domain="$domain" '
+{ certs[NR] = $0 }
+END {
+  if (NR > 0) {
+    print "Removing the certificates from the " domain "."
+    for (i=1; i<=NR; i++) {
+      system("rm -f " certs[i])
+    }
+  } else {
+    print "No certificates found for the " domain "."
+  }
+}'
+    done
+    ;;
+  create)
+    for domain in "${domains[@]}"; do
+      pem="$certs_path/$domain.pem"
+      key="$certs_path/$domain.key"
+      /opt/mkcert/bin/current \
+        -ecdsa \
+        -cert-file "$pem" \
+        -key-file "$key" \
+        "$domain" "*.$domain" >/dev/null 2>&1 &&
+        cat "$key" "$pem" | tee "$pem" >/dev/null 2>&1 &&
+        echo "Certificate generated for $domain." &&
+        continue
+      echo "No certificate generated for $domain."
+    done
+    ;;
+  *) __mkcert__usage ;;
+  esac
+}
+
+[ $# -eq 0 ] && __mkcert__usage
+__mkcert "$@"
